apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-sep4-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-sep4-1:a8769d11b89286212cc99bddce59d7d77305ec5a@sha256:3e534970a95bf11760d53332c4197faeb6110be9402bb07fe9b7563ca63a21e6 # use pre-built to bootstrap 
          name: app-inference
